name: Generate and Publish Javadoc

on:
  workflow_run:
    workflows: [ "Maven Package and Deploy" ]
    types:
      - completed

jobs:
  javadoc:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load Environment Variables
        run: .github/workflows/scripts/set-env-vars.sh

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Generate Javadoc
        run: mvn javadoc:javadoc -Dmaven.javadoc.failOnError=false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./target/site/apidocs/
